version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017

  flask_app:
    build:
      context: .
    container_name: flask_app
    depends_on:
      - mongo
    volumes:
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./data:/app/data   # Mount the 'data' folder into the container
    ports:
      - "5000:5000"
